apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app
        image: a3nktr0/inventory-app:latest
        ports:
        - containerPort: 8080 # Updated to match the application's expected port
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "4"
        env:
        - name: INVENTORY_PORT
          valueFrom:
            secretKeyRef:
              name: orchestrator-secrets
              key: INVENTORY_PORT
        - name: INVENTORY_DB_HOST
          valueFrom:
            secretKeyRef:
              name: orchestrator-secrets
              key: INVENTORY_HOST
        - name: INVENTORY_USER
          valueFrom:
            secretKeyRef:
              name: orchestrator-secrets
              key: INVENTORY_USER
        - name: INVENTORY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orchestrator-secrets
              key: INVENTORY_PASSWORD
        - name: INVENTORY_DB_NAME
          valueFrom:
            secretKeyRef:
              name: orchestrator-secrets
              key: INVENTORY_DB_NAME
        envFrom:
        - secretRef:
            name: orchestrator-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-app
spec:
  clusterIP: None # Added to create a headless service for DNS resolution
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inventory-app
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-app-external # Separate service for external access
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003 # NodePort for accessing inventory-app externally
  selector:
    app: inventory-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60